In [1]:
import pandas as pd

In [2]:
hd = pd.read_csv('USA_Housing.csv')

In [3]:
hd

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386
...,...,...,...,...,...,...,...
4995,60567.944140,7.830362,6.137356,3.46,22837.361035,1.060194e+06,USNS Williams\nFPO AP 30153-7653
4996,78491.275435,6.999135,6.576763,4.02,25616.115489,1.482618e+06,"PSC 9258, Box 8489\nAPO AA 42991-3352"
4997,63390.686886,7.250591,4.805081,2.13,33266.145490,1.030730e+06,"4215 Tracy Garden Suite 076\nJoshualand, VA 01..."
4998,68001.331235,5.534388,7.130144,5.44,42625.620156,1.198657e+06,USS Wallace\nFPO AE 73316
4999,65510.581804,5.992305,6.792336,4.07,46501.283803,1.298950e+06,"37778 George Ridges Apt. 509\nEast Holly, NV 2..."

In [4]:
hd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object
dtypes: float64(6), object(1)
memory usage: 273.6+ KB

In [5]:
hd.drop('Address',axis=1,inplace = True)

In [6]:
hd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
dtypes: float64(6)
memory usage: 234.5 KB

### Spliting x and y

In [7]:
y = hd['Price']

In [8]:
x = hd.drop('Price',axis = 1)

In [9]:
hd

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05
...,...,...,...,...,...,...
4995,60567.944140,7.830362,6.137356,3.46,22837.361035,1.060194e+06
4996,78491.275435,6.999135,6.576763,4.02,25616.115489,1.482618e+06
4997,63390.686886,7.250591,4.805081,2.13,33266.145490,1.030730e+06
4998,68001.331235,5.534388,7.130144,5.44,42625.620156,1.198657e+06
4999,65510.581804,5.992305,6.792336,4.07,46501.283803,1.298950e+06

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [12]:
y_test

1501    1.339096e+06
2586    1.251794e+06
2653    1.340095e+06
1055    1.431508e+06
705     1.042374e+06
            ...
4711    1.107031e+06
2313    1.405505e+06
3214    1.924156e+06
2732    1.571254e+06
1926    8.831475e+05
Name: Price, Length: 1000, dtype: float64

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
Martins_lin_model = LinearRegression()

In [15]:
Martins_lin_model.fit(x_train,y_train)

LinearRegression()

In [16]:
Martins_lin_model.coef_

array([2.16522058e+01, 1.64666481e+05, 1.19624012e+05, 2.44037761e+03,
       1.52703134e+01])

In [17]:
Martins_lin_model.intercept_

np.float64(-2635072.9009313574)

In [18]:
predictions = Martins_lin_model.predict(x_test)

In [19]:
result = pd.DataFrame(predictions,columns=['Prediction'])

In [20]:
result
new_y_test = y_test.reset_index(drop=True)

In [21]:
result['Y_test'] = new_y_test

In [22]:
result['Error'] = result['Prediction'] - result['Y_test']

In [23]:
result

       Prediction        Y_test          Error
0    1.308588e+06  1.339096e+06  -30508.150248
1    1.237037e+06  1.251794e+06  -14756.949343
2    1.243429e+06  1.340095e+06  -96665.625898
3    1.228900e+06  1.431508e+06 -202607.409824
4    1.063321e+06  1.042374e+06   20947.383011
..            ...           ...            ...
995  1.042903e+06  1.107031e+06  -64128.670938
996  1.318532e+06  1.405505e+06  -86973.442133
997  1.870001e+06  1.924156e+06  -54154.099527
998  1.663624e+06  1.571254e+06   92370.326701
999  1.045097e+06  8.831475e+05  161949.079535

[1000 rows x 3 columns]

In [24]:
result_co = pd.DataFrame(Martins_lin_model.coef_, columns=['Coeff'])

In [25]:
x_train.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population'],
      dtype='object')

In [26]:
result_co['Features'] = x_train.columns

In [27]:
result_co

           Coeff                      Features
0      21.652206              Avg. Area Income
1  164666.480722           Avg. Area House Age
2  119624.012232     Avg. Area Number of Rooms
3    2440.377611  Avg. Area Number of Bedrooms
4      15.270313               Area Population

In [28]:
import joblib

In [29]:
joblib.dump(Martins_lin_model,'Martins_lin_model.pkl')

['Martins_lin_model.pkl']

In [30]:
import numpy as np

In [31]:
inputs = np.array([10000,5,2,4,23000]).reshape(1,-1)

In [32]:
Martins_lin_model.predict(np.array([10000,5,2,4,23000]).reshape(1,-1))

C:\Users\PC\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([-994991.6958895])

In [33]:
from sklearn.metrics import r2_score

In [35]:

r2_score(y_test,predictions)

0.9179971706834579